# Generated by Django 3.1.6 on 2022-08-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30, verbose_name='Наименование банка')),
                ('rate_min', models.PositiveSmallIntegerField(help_text='Введите ставку в процентах', verbose_name='Минимальная ипотечная ставка')),
                ('rate_max', models.PositiveSmallIntegerField(help_text='Введите ставку в процентах', verbose_name='Максимальная ипотечная ставка')),
                ('payment_min', models.PositiveIntegerField(help_text='Месячный платеж в рублях без копеек', verbose_name='Минимальный платеж по ипотеке')),
                ('payment_max', models.PositiveIntegerField(help_text='Месячный платеж в рублях без копеек', verbose_name='Максимальный платеж по ипотеке')),
                ('term_min', models.PositiveIntegerField(help_text='Срок ипотеки в годах', verbose_name='Минимальный срок ипотеки')),
                ('term_max', models.PositiveIntegerField(help_text='Срок ипотеки в годах', verbose_name='Максимальный срок ипотеки')),
            ],
            options={
                'verbose_name': 'Предложение банка',
                'verbose_name_plural': 'Предложения банков',
            },
        ),
    ]
