# Generated by Django 3.1.6 on 2022-08-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankoffer',
            name='payment',
            field=models.PositiveIntegerField(help_text='Расчетный месячный платеж в рублях без копеек', null=True, verbose_name='Платеж по ипотеке'),
        ),
    ]
