# Generated by Django 3.1.6 on 2022-08-04 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_bankoffer_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankoffer',
            name='payment',
        ),
        migrations.AlterField(
            model_name='bankoffer',
            name='bank_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Наименование банка'),
        ),
        migrations.AlterField(
            model_name='bankoffer',
            name='payment_max',
            field=models.PositiveIntegerField(help_text='Максимальный размер кредита в рублях без копеек', verbose_name='Максимальный размер кредита'),
        ),
        migrations.AlterField(
            model_name='bankoffer',
            name='payment_min',
            field=models.PositiveIntegerField(help_text='Минимальный размер кредита в рублях без копеек', verbose_name='Минимальный размер кредита'),
        ),
        migrations.AlterField(
            model_name='bankoffer',
            name='rate_max',
            field=models.FloatField(help_text='Введите ставку в процентах', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Максимальная ипотечная ставка'),
        ),
        migrations.AlterField(
            model_name='bankoffer',
            name='rate_min',
            field=models.FloatField(help_text='Введите ставку в процентах', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Минимальная ипотечная ставка'),
        ),
    ]
